apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-bot
  labels:
    app: trading-bot
spec:
  replicas: 3  # Scale horizontally
  selector:
    matchLabels:
      app: trading-bot
  template:
    metadata:
      labels:
        app: trading-bot
    spec:
      containers:
        - name: trading-bot
          image: your-dockerhub-user/trading-bot:latest
          ports:
            - containerPort: 5000
            - containerPort: 6789
          env:
            - name: USE_LIVE_TRADING
              value: "False"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: trading-bot-service
spec:
  selector:
    app: trading-bot
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
