FROM node:18-alpine AS build

WORKDIR /app/frontend

# Copy only frontend-related files
COPY frontend /app/frontend

RUN npm install && npm run build

FROM nginx:alpine
COPY --from=build /app/frontend/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
