FROM python:3.10-slim

WORKDIR /app

# Copy only necessary data feed script and requirements
COPY data_feed.py /app/data_feed.py
COPY requirements_data_feed.txt /app/requirements_data_feed.txt

RUN pip install --no-cache-dir -r requirements_data_feed.txt

EXPOSE 5001

CMD ["python", "data_feed.py"]
