FROM python:3.10-slim

WORKDIR /app/broker

# Copy only broker-related files
COPY broker /app/broker

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5004

CMD ["python", "real_broker.py"]
